version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth
    container_name: auth-service
    expose:
      - "3000"
    depends_on:
      - mongo
  public-service:
    build: ./public
    container_name: public-service
    expose:
      - "3000"
    depends_on:
      - auth-service
  private-service:
    build: ./private
    container_name: private-service
    expose:
      - "3000"
    depends_on:
      - auth-service

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - auth-service

volumes:
  mongo-data: